# docker-compose configuration file
version: "2"

# CONTAINERS
services:

  #--- LDAP ---#
  # Local user database. All services have a unified view on user accounts.
  ldap:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/ldap:v0.2
    container_name: ldap
    hostname: ldap
    #domainname: demonet
    volumes:
      - ${LDAP_DB}:/var/lib/ldap
      - ${LDAP_CF}:/etc/ldap/slapd.d
    env_file:
      - .env

  # Add demo users on the LDAP server
  ldap-ldapadd:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/ldap:v0.2
    container_name: ldap-add
    depends_on:
      - ldap
    links:
      - ldap
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
    env_file:
      - .env
    entrypoint: bash /root/addusers.sh


  #--- EOS Storage ---#
  # EOS Server: One headnote (MGM - namespace + management), one message queue (MQ), four storage servers (FST)
  eos-mgm:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-mgm
    hostname: eos-mgm
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_MGM}:/var/eos
    env_file:
      - .env
    environment:
      EOS_ROLE: "mgm"

  eos-mq:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-mq
    hostname: eos-mq
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_MQ}:/var/eos
    env_file:
      - .env
    environment:
      EOS_ROLE: "mq"

  eos-fst1:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-fst1
    hostname: eos-fst1
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_FST_1}:/var/eos
      - ${EOS_FST_USERDATA_1}:/${FST_MOUNTPOINT}
    env_file:
      - .env
    environment:
      EOS_ROLE: "fst"

  eos-fst2:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-fst2
    hostname: eos-fst2
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_FST_2}:/var/eos
      - ${EOS_FST_USERDATA_2}:/${FST_MOUNTPOINT}
    env_file:
      - .env
    environment:
      EOS_ROLE: "fst"

  eos-fst3:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-fst3
    hostname: eos-fst3
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_FST_3}:/var/eos
      - ${EOS_FST_USERDATA_3}:/${FST_MOUNTPOINT}
    env_file:
      - .env
    environment:
      EOS_ROLE: "fst"

  eos-fst4:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-storage:v0.9
    container_name: eos-fst4
    hostname: eos-fst4
    domainname: demonet
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${EOS_FST_4}:/var/eos
      - ${EOS_FST_USERDATA_4}:/${FST_MOUNTPOINT}
    env_file:
      - .env
    environment:
      EOS_ROLE: "fst"


  #--- CERNBox ---#
  # Web User Interface (httpd, php, sqlite)
  cernbox:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/cernbox:v1.1
    container_name: cernbox
    hostname: cernbox
    domainname: demonet
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
    env_file:
      - .env

  cernboxmysql:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/cernboxmysql:v1.0
    container_name: cernboxmysql
    hostname: cernboxmysql
    domainname: demonet
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - ${CERNBOX_MYSQL}:/var/lib/mysql
    env_file:
      - .env

  # Nginx gateway
  cernboxgateway:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/cernboxgateway:v1.0
    container_name: cernboxgateway
    hostname: cernboxgateway
    domainname: demonet
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
    env_file:
      - .env


  #--- SWAN ---#
  # Jupyterhub: User authentication and session management
  jupyterhub:
    image: gitlab-registry.cern.ch/swan/docker-images/jupyterhub:v1.1
    container_name: jupyterhub
    ports:
      - ${SWAN_HTTPS_PORT}:443
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file:
      - .env

  # Cern VM FileSystem: Access to scientific libraries via the WLCG
  cvmfs:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/cvmfs:v0.5
    container_name: cvmfs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor=unconfined
    volumes:
      - ${CVMFS_FOLDER}:/cvmfs:shared
    env_file:
      - .env

  # EOS-Fuse: Access to EOS storage (same as CERNBox)
  eos-fuse:
    image: gitlab-registry.cern.ch/cernbox/boxedhub/eos-fuse:v0.7
    container_name: eos-fuse
    hostname: eos-fuse
    domainname: demonet
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    pid: host
    security_opt:
      - apparmor=unconfined
    volumes:
      - ${HOST_FOLDER}:${HOST_FOLDER}
      - /sys/fs/cgroup
      - ${EOS_FOLDER}:/eos:shared
    env_file:
      - .env



# NETWORKS
networks:
  default:
    external:
      name: demonet



# VOLUMES
volumes:

  # LDAP
  ldap_database:
    external:
      name: ${LDAP_DB}
  ldap_config:
    external:
      name: ${LDAP_CF}

  # EOS
  eos-fst_1:
    external:
      name: ${EOS_FST_1}
  eos-fst_userdata_1:
    external:
      name: ${EOS_FST_USERDATA_1}

  eos-fst_2:
    external:
      name: ${EOS_FST_2}
  eos-fst_userdata_2:
    external:
      name: ${EOS_FST_USERDATA_2}

  eos-fst_3:
    external:
      name: ${EOS_FST_3}
  eos-fst_userdata_3:
    external:
      name: ${EOS_FST_USERDATA_3}
  
  eos-fst_4:
    external:
      name: ${EOS_FST_4}
  eos-fst_userdata_4:
    external:
      name: ${EOS_FST_USERDATA_4}
  
  eos-mgm:
    external:
      name: ${EOS_MGM} 
  
  eos-mq:
    external:
      name: ${EOS_MQ}

  # CERNBox
  cernbox_mysql:
    external:
      name: ${CERNBOX_MYSQL}

